#! /usr/bin/env -S python3 -u

import os
import sys
import argparse
import subprocess

from pathlib import Path

MYPATH = Path(__file__).parent
ROOT = MYPATH.parent
VCPKG_ROOT = os.environ.get('VCPKG_ROOT')

def is_anything_staged():
    proc = subprocess.run(['git', 'diff', '--cached', '--quiet'], cwd=ROOT, check=False)
    return proc.returncode != 0

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('message', help='main commit message')
    args = parser.parse_args()

    message: str = args.message

    if VCPKG_ROOT is None:
        print('VCPKG_ROOT environment variable not set', file=sys.stderr)
        sys.exit(1)

    if is_anything_staged():
        print("You have staged changes, update cannot be performed", file=sys.stderr)
        sys.exit(1)
    subprocess.run(['git', 'add', 'ports/.'], cwd=ROOT, check=True)
    if not is_anything_staged():
        print("Nothing to update")
        sys.exit(0)

    cur_branch = subprocess.run(['git', 'symbolic-ref', '--short', 'HEAD'], cwd=ROOT, 
                         stdout=subprocess.PIPE, check=True).stdout.decode('utf-8').strip()
    subprocess.run(['git', 'switch', '-c', 'update-work'], cwd=ROOT, check=True)
    subprocess.run(['git', 'commit', '-m', message], cwd=ROOT, check=True)
    subprocess.run([Path(VCPKG_ROOT) / 'vcpkg', 
                    '--x-builtin-ports-root=./ports', 
                    '--x-builtin-registry-versions-dir=./versions', 
                    'x-add-version', '--all', '--verbose'], cwd=ROOT, check=True)
    subprocess.run(['git', 'add', 'versions/.'], cwd=ROOT, check=True)
    subprocess.run(['git', 'commit', '-m', 'Updating versions'], cwd=ROOT, check=True)
    subprocess.run(['git', 'switch', cur_branch], cwd=ROOT, check=True)
    subprocess.run(['git', 'merge', '--squash', 'update-work'], cwd=ROOT, check=True)
    subprocess.run(['git', 'commit', '-m', message], cwd=ROOT, check=True)
    subprocess.run(['git', 'branch', '-D', 'update-work'], cwd=ROOT, check=True)


if __name__ == '__main__':
    main()
